// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUilHcCNifRq4w4QguYLuU7kSysJ5jPcM',
    appId: '1:658715402627:web:b2fb7d7fac5e1e26c316b6',
    messagingSenderId: '658715402627',
    projectId: 'fullbackendfirebaseservices',
    authDomain: 'fullbackendfirebaseservices.firebaseapp.com',
    storageBucket: 'fullbackendfirebaseservices.appspot.com',
    measurementId: 'G-W893FFX6EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_8q2qugyqo19sdRgXFTnETbZg7dcrKUQ',
    appId: '1:658715402627:android:2cd2eb96d7a0d2a4c316b6',
    messagingSenderId: '658715402627',
    projectId: 'fullbackendfirebaseservices',
    storageBucket: 'fullbackendfirebaseservices.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxT9-ZRXNGt8XGuNGTv-lQJM3Tv1s0mo',
    appId: '1:658715402627:ios:8fcba64d47c3b7a9c316b6',
    messagingSenderId: '658715402627',
    projectId: 'fullbackendfirebaseservices',
    storageBucket: 'fullbackendfirebaseservices.appspot.com',
    iosBundleId: 'com.example.firebaseBackendServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxT9-ZRXNGt8XGuNGTv-lQJM3Tv1s0mo',
    appId: '1:658715402627:ios:eacdc47642e1081dc316b6',
    messagingSenderId: '658715402627',
    projectId: 'fullbackendfirebaseservices',
    storageBucket: 'fullbackendfirebaseservices.appspot.com',
    iosBundleId: 'com.example.firebaseBackendServiceApp.RunnerTests',
  );
}
